"use client";

import { useEffect, useMemo, useState } from "react";
import type { IndividualLesson, Person } from "@/lib/people";
import { formatWeekRange, getCurrentWeek, getLessonsForWeek, getSubgroupSubjects, type GroupPreference, type Rehearsal, type ScheduleData } from "@/lib/schedule";

const PERSON_KEY="schedule_person_id";
const mins=(v:string)=>{const [h,m]=v.split(":").map(Number);return h*60+m};
const dateKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const todayIndex=()=>{const d=new Date().getDay();return d===0?-1:d-1};
const todayDate=(i:number)=>{const d=new Date();d.setDate(d.getDate()+i-(d.getDay()-1));return d};
const noteKey=(date:string,start:string,title:string)=>`${date}|${start}|${title}`;
type Event={kind:"group"|"individual"|"rehearsal";start:string;end:string;title:string;subtitle:string;detail:string;note?:string;key:string};

export default function DashboardV2(){
 const [people,setPeople]=useState<Person[]>([]),[person,setPerson]=useState<Person|null>(null),[schedule,setSchedule]=useState<ScheduleData|null>(null),[individuals,setIndividuals]=useState<IndividualLesson[]>([]),[rehearsals,setRehearsals]=useState<Rehearsal[]>([]),[preferences,setPreferences]=useState<Record<string,GroupPreference>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[now,setNow]=useState(new Date()),[noteEvent,setNoteEvent]=useState<Event|null>(null),[noteText,setNoteText]=useState(""),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true);
 const loadProfile=async(id:string)=>{const [sr,ir]=await Promise.all([fetch(`/api/profile/settings?personId=${encodeURIComponent(id)}`,{cache:"no-store"}),fetch(`/api/individuals?personId=${encodeURIComponent(id)}`,{cache:"no-store`})]);if(sr.ok){const d=await sr.json();setPreferences(d.preferences??{});setNotes(d.notes??{})}if(ir.ok)setIndividuals((await ir.json()).lessons??[])};
 useEffect(()=>{const id=localStorage.getItem(PERSON_KEY),today=dateKey(new Date());Promise.all([fetch("/api/people",{cache:"no-store"}).then(r=>r.json()),fetch(`/api/schedule?date=${today}`,{cache:"no-store"}).then(r=>r.json())]).then(([p,s])=>{const list=p.people??[];const chosen=list.find((x:Person)=>x.id===id)??null;setPeople(list);setPerson(chosen);setSchedule(s.schedule??null);setRehearsals(s.rehearsals??[]);if(chosen)void loadProfile(chosen.id);}).finally(()=>setLoading(false))},[]);
 useEffect(()=>{const t=setInterval(()=>setNow(new Date()),10000);return()=>clearInterval(t)},[]);
 const today=todayIndex(),week=schedule?getCurrentWeek(schedule,now):1,todayKey=dateKey(today>=0?todayDate(today):now);
 const groups=schedule&&today>=0?getLessonsForWeek(schedule,today,week,preferences):[];
 const events=useMemo<Event[]>(()=>[...groups.map(x=>({kind:"group" as const,start:x.timeStart,end:x.timeEnd,title:x.class,subtitle:x.professor,detail:x.auditorium,key:noteKey(todayKey,x.timeStart,x.class)})),...individuals.filter(x=>x.date===todayKey).map(x=>({kind:"individual" as const,start:x.timeStart,end:x.timeEnd,title:x.subject,subtitle:`Индивидуальное · ${x.professor}`,detail:x.auditorium,note:x.note,key:x.id})),...rehearsals.filter(x=>x.date===todayKey).map(x=>({kind:"rehearsal" as const,start:x.timeStart,end:x.timeEnd,title:x.subject,subtitle:"Репетиция",detail:x.responsible,key:x.id}))].sort((a,b)=>mins(a.start)-mins(b.start)),[groups,individuals,rehearsals,todayKey]);
 const currentMin=now.getHours()*60+now.getMinutes(),current=events.find(e=>mins(e.start)<=currentMin&&mins(e.end)>currentMin),next=events.find(e=>mins(e.start)>currentMin),past=(e:Event)=>mins(e.end)<=currentMin;
 const countdown=(v:string)=>{const d=mins(v)-currentMin;if(d<=0)return "сейчас";const h=Math.floor(d/60),m=d%60;return h?`${h} ч ${m} мин`:`${m} мин`};
 const progress=current?Math.round(Math.min(100,Math.max(0,(currentMin-mins(current.start))/(mins(current.end)-mins(current.start))*100))):0;
 const select=(p:Person)=>{localStorage.setItem(PERSON_KEY,p.id);setPerson(p);void loadProfile(p.id)};
 const logout=()=>{localStorage.removeItem(PERSON_KEY);window.location.href="/"};
 const openNote=(e:Event)=>{setNoteEvent(e);setNoteText(notes[e.key]??"")};
 const saveNote=async()=>{if(!person||!noteEvent)return;const nextNotes={...notes};if(noteText.trim())nextNotes[noteEvent.key]=noteText.trim();else delete nextNotes[noteEvent.key];setSaving(true);try{const r=await fetch("/api/profile/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({personId:person.id,preferences,notes:nextNotes})});if(r.ok){setNotes(nextNotes);setNoteEvent(null)}}finally{setSaving(false)}};
 if(loading)return <main className="dashboard-v2"><div className="dashboard-empty">Загрузка…</div></main>;
 if(!person)return <main className="dashboard-v2 dashboard-choose"><p className="dashboard-kicker">214Р · РАСПИСАНИЕ</p><h1>Кто сегодня<br/>учится?</h1><p>Выбери своё имя.</p><div className="dashboard-people">{people.map(p=><button key={p.id} onClick={()=>select(p)}><span>{p.name[0]}</span><strong>{p.name}</strong><b>→</b></button>)}</div></main>;
 return <main className="dashboard-v2"><header className="dashboard-v2-head"><div><p className="dashboard-kicker">214Р · ДАШБОРД</p><h1>Привет, {person.name.split(" ")[0]}.</h1><p>{new Intl.DateTimeFormat("ru-RU",{weekday:"long",day:"numeric",month:"long"}).format(now)}</p></div><button className="dashboard-profile" onClick={logout}><span>{person.name}</span><small>Выйти</small></button></header>
 <section className="dashboard-focus"><div className="dashboard-focus-top"><span>{current?"Сейчас идёт":"Следующая пара"}</span><em>{current?`${progress}%`:next?`через ${countdown(next.start)}`:""}</em></div><h2>{current?.title??next?.title??"На сегодня всё"}</h2>{current?<><p>{current.subtitle} · {current.detail}</p><strong>до конца · {countdown(current.end)}</strong><div className="dashboard-progress"><i style={{width:`${progress}%`}}/></div><div className="dashboard-progress-labels"><span>{current.start}</span><span>{current.end}</span></div></>:next?<p>{next.subtitle} · {next.detail}</p>:<p>Можно спокойно отдыхать.</p>}</section>
 <section className="dashboard-stats"><article><span>Следующая</span><strong>{next?.title??"—"}</strong><small>{next?`${next.start}–${next.end}`:"Больше пар нет"}</small></article><article><span>Сегодня</span><strong>{events.length}</strong><small>занятий</small></article><article><span>Неделя</span><strong>№ {week}</strong><small>{formatWeekRange(schedule,week)}</small></article></section>
 <section className="dashboard-timeline"><div className="dashboard-section-head"><h2>Сегодня</h2><span>{events.length}</span></div>{events.length?events.map(e=><article className={`dashboard-event-v2 ${e.kind} ${current===e?"current":""} ${past(e)?"past":""}`} key={e.key}><div className="dashboard-event-time"><strong>{e.start}</strong><small>{e.end}</small></div><div className="dashboard-event-content"><span>{e.kind==="individual"?"ИНДИВИДУАЛЬНО":e.kind==="rehearsal"?"РЕПЕТИЦИЯ":"ПАРА"}</span><h3>{e.title}</h3><p>{e.subtitle} · {e.detail}</p>{(e.note||notes[e.key])&&<small className="dashboard-note-preview">● {e.note||notes[e.key]}</small>}</div>{e.kind==="group"&&<button className="dashboard-note" onClick={()=>openNote(e)}>{notes[e.key]?"Изменить":"Заметка"}</button>}</article>):<div className="dashboard-empty">На сегодня занятий нет.</div>}</section>
 {noteEvent&&<div className="dashboard-overlay" onMouseDown={()=>setNoteEvent(null)}><section className="dashboard-note-modal" onMouseDown={e=>e.stopPropagation()}><div><span>ЛИЧНАЯ ЗАМЕТКА</span><button onClick={()=>setNoteEvent(null)}>×</button></div><h2>{noteEvent.title}</h2><p>{noteEvent.start}–{noteEvent.end}</p><textarea value={noteText} onChange={e=>setNoteText(e.target.value)} maxLength={2000} placeholder="Например: взять ноты…" autoFocus/><footer><button onClick={()=>setNoteEvent(null)}>Отмена</button><button disabled={saving} onClick={()=>void saveNote()}>{saving?"Сохраняю…":"Сохранить"}</button></footer></section></div>}
 </main>;
}
