"use client";

import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from "react";
import styles from "./HeadmanPanel.module.css";
import type { Person } from "@/lib/people";
import { ATTENDANCE_REASON_LABELS, attendanceReasonText, type AttendanceReport } from "@/lib/attendance";

type Overview={actor:Person;reports:AttendanceReport[];people:Person[]};
type ReportFilter="today"|"upcoming"|"all";
const localDateKey=()=>{const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")};
const shortDate=(value:string)=>value.split("-").reverse().join(".");

export default function HeadmanPanel(){
  const [overview,setOverview]=useState<Overview|null>(null),[loading,setLoading]=useState(true),[filter,setFilter]=useState<ReportFilter>("today"),[status,setStatus]=useState(""),[busy,setBusy]=useState(false);
  const [announcementTitle,setAnnouncementTitle]=useState(""),[announcementBody,setAnnouncementBody]=useState(""),[announcementAudience,setAnnouncementAudience]=useState<"all"|"selected">("all"),[announcementSelected,setAnnouncementSelected]=useState<string[]>([]),[announcementPush,setAnnouncementPush]=useState(false);
  const [angerSelected,setAngerSelected]=useState<string[]>([]),[angerType,setAngerType]=useState<"late"|"absence">("late");
  const load=async()=>{setLoading(true);try{const response=await fetch("/api/headman/overview",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error??"Не удалось загрузить панель");setOverview(data)}catch(error){setStatus(error instanceof Error?error.message:"Не удалось загрузить панель")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const today=localDateKey(),people=overview?.people??[],reports=overview?.reports??[];
  const appliesToday=(report:AttendanceReport)=>report.dateFrom<=today&&report.dateTo>=today;
  const lateToday=reports.filter(report=>report.kind==="late"&&report.dateFrom===today),absentToday=reports.filter(report=>report.kind==="absence"&&appliesToday(report));
  const absentPeopleToday=new Set(absentToday.map(report=>report.personId)).size,periodReports=reports.filter(report=>report.kind==="absence"&&report.scope==="period"&&report.dateTo>=today),new24=reports.filter(report=>Date.now()-Date.parse(report.updatedAt)<86_400_000).length;
  const visible=useMemo(()=>reports.filter(report=>filter==="all"||filter==="today"?filter==="all"||report.dateFrom<=today&&report.dateTo>=today:report.dateTo>=today),[reports,filter,today]);
  const reasonCounts={sick:reports.filter(r=>r.reason==="sick"&&r.dateTo>=today).length,event:reports.filter(r=>r.reason==="event"&&r.dateTo>=today).length,other:reports.filter(r=>r.reason==="other"&&r.dateTo>=today).length};
  const toggle=(setter:Dispatch<SetStateAction<string[]>>,id:string)=>setter(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
  const sendAnnouncement=async()=>{if(busy||!announcementTitle.trim()||!announcementBody.trim()||(announcementAudience==="selected"&&!announcementSelected.length))return;setBusy(true);setStatus("");try{const response=await fetch("/api/headman/announcements",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:announcementTitle,body:announcementBody,audience:announcementAudience,recipientIds:announcementSelected,sendPush:announcementPush})});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error??"Не удалось опубликовать");setAnnouncementTitle("");setAnnouncementBody("");setAnnouncementSelected([]);setAnnouncementPush(false);setStatus("Объявление опубликовано"+(data.delivery?" · Push "+(data.delivery.sent??0)+"/"+(data.delivery.subscriptions??0):""))}catch(error){setStatus(error instanceof Error?error.message:"Не удалось опубликовать")}finally{setBusy(false)}};
  const sendAnger=async()=>{if(busy||!angerSelected.length)return;setBusy(true);setStatus("");try{const response=await fetch("/api/headman/reminders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recipients:angerSelected,type:angerType})});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error??"Не удалось отправить");setStatus("Строгое напоминание отправлено · "+(data.delivery?.sent??0)+"/"+(data.delivery?.subscriptions??0)+" устройств");setAngerSelected([])}catch(error){setStatus(error instanceof Error?error.message:"Не удалось отправить")}finally{setBusy(false)}};
  const reportText=(report:AttendanceReport)=>{if(report.kind==="late")return "Опоздает на «"+(report.lessonTitle??"пару")+"» · "+(report.lessonStart??"");const reason=attendanceReasonText(report);if(report.scope==="lesson")return "Не будет на «"+(report.lessonTitle??"паре")+"» · "+shortDate(report.dateFrom)+" · "+reason;if(report.scope==="day")return "Не будет весь день · "+shortDate(report.dateFrom)+" · "+reason;return "Не будет "+shortDate(report.dateFrom)+"–"+shortDate(report.dateTo)+" · "+reason};
  if(loading&&!overview)return <main className={styles.page}><p>Загружаем сводку…</p></main>;
  return <main className={styles.page}>
    <header className={styles.head}><div><p className="eyebrow">214Р · ПАНЕЛЬ СТАРОСТЫ</p><h1>Сводка группы</h1><p>{overview?.actor.name??"Староста"} · опоздания, отсутствия и коммуникация</p></div><button className={styles.refresh} type="button" disabled={loading} onClick={()=>void load()}>↻ Обновить</button></header>
    <section className={styles.summary}><article className={styles.card}><span>Опоздают сегодня</span><strong>{lateToday.length}</strong><small>{new Set(lateToday.map(item=>item.personId)).size} человек</small></article><article className={styles.card}><span>Не будет сегодня</span><strong>{absentPeopleToday}</strong><small>{absentToday.length} отметок</small></article><article className={styles.card}><span>Периоды</span><strong>{periodReports.length}</strong><small>актуальных заявок</small></article><article className={styles.card}><span>Новое</span><strong>{new24}</strong><small>за последние 24 часа</small></article></section>
    <section className={styles.grid}>
      <article className={styles.panel}><header><div><h2>Опоздания и отсутствия</h2><span>{visible.length} записей</span></div><div className={styles.filters}><button className={filter==="today"?styles.active:""} onClick={()=>setFilter("today")}>Сегодня</button><button className={filter==="upcoming"?styles.active:""} onClick={()=>setFilter("upcoming")}>Актуальные</button><button className={filter==="all"?styles.active:""} onClick={()=>setFilter("all")}>Все</button></div></header><div className={styles.reasonSummary}><span>{ATTENDANCE_REASON_LABELS.sick}: {reasonCounts.sick}</span><span>{ATTENDANCE_REASON_LABELS.event}: {reasonCounts.event}</span><span>{ATTENDANCE_REASON_LABELS.other}: {reasonCounts.other}</span></div><div className={styles.reports}>{visible.length?visible.map(report=><div className={styles.report} key={report.id}><div className={styles.avatar}>{report.personName.trim().charAt(0).toUpperCase()}</div><div><strong>{report.personName}</strong><p>{reportText(report)}</p><small>Обновлено {new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(report.updatedAt))}</small></div><span className={styles.badge+" "+(report.kind==="late"?styles.badgeLate:styles.badgeAbsence)}>{report.kind==="late"?"ОПОЗДАНИЕ":"ОТСУТСТВИЕ"}</span></div>):<div className={styles.empty}>Нет отметок для этого фильтра</div>}</div></article>
      <div className={styles.forms}>
        <section className={styles.panel+" "+styles.form}><p className="eyebrow">Объявление</p><h2>Написать группе</h2><p>Создай объявление на дашборде и при необходимости продублируй его Push.</p><label className={styles.field}>Заголовок<input maxLength={120} value={announcementTitle} onChange={e=>setAnnouncementTitle(e.target.value)} placeholder="Например, После пары сбор"/></label><label className={styles.field}>Текст<textarea rows={4} maxLength={1200} value={announcementBody} onChange={e=>setAnnouncementBody(e.target.value)} placeholder="Что нужно сообщить…"/></label><div className={styles.chips}><button className={announcementAudience==="all"?styles.active:""} onClick={()=>setAnnouncementAudience("all")}>Всем</button><button className={announcementAudience==="selected"?styles.active:""} onClick={()=>setAnnouncementAudience("selected")}>Выбранным</button></div>{announcementAudience==="selected"&&<div className={styles.chips}>{people.map(person=><button type="button" key={person.id} className={announcementSelected.includes(person.id)?styles.active:""} onClick={()=>toggle(setAnnouncementSelected,person.id)}>{person.name}</button>)}</div>}<button type="button" className={styles.pushToggle} aria-pressed={announcementPush} onClick={()=>setAnnouncementPush(value=>!value)}><span><strong>Отправить Push</strong><small>Продублировать объявление уведомлением</small></span><i aria-hidden="true"><u/></i></button><div className={styles.actions}><button className={styles.primary} disabled={busy||!announcementTitle.trim()||!announcementBody.trim()||(announcementAudience==="selected"&&!announcementSelected.length)} onClick={()=>void sendAnnouncement()}>Опубликовать</button></div></section>
        <section className={styles.panel+" "+styles.form}><p className="eyebrow">Кнопка гнева 😡</p><h2>Строгое напоминание</h2><p>Выбери людей и отправь жёсткое, но без оскорблений, Push-напоминание про опоздания или прогулы.</p><div className={styles.chips}><button className={angerType==="late"?styles.active:""} onClick={()=>setAngerType("late")}>Опоздание</button><button className={angerType==="absence"?styles.active:""} onClick={()=>setAngerType("absence")}>Прогул</button></div><div className={styles.chips}>{people.filter(person=>person.id!==overview?.actor.id).map(person=><button type="button" key={person.id} className={angerSelected.includes(person.id)?styles.active:""} onClick={()=>toggle(setAngerSelected,person.id)}>{person.name}</button>)}</div><div className={styles.actions}><button className={styles.angry} disabled={busy||!angerSelected.length} onClick={()=>void sendAnger()}>Отправить строгое Push · {angerSelected.length}</button></div></section>
        {status&&<p className={styles.status} role="status">{status}</p>}
      </div>
    </section>
  </main>;
}
