import { createHmac } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";
import { deleteIndividualLesson, getIndividualLessons, saveIndividualLesson } from "@/lib/database";

const SECRET = process.env.ADMIN_SESSION_SECRET ?? process.env.ADMIN_PASSWORD;
const COOKIE = "schedule_admin";
function auth(request: NextRequest) { const token = SECRET ? createHmac("sha256", SECRET).update("schedule-admin").digest("hex") : null; return Boolean(token && request.cookies.get(COOKIE)?.value === token); }
function okTime(v: unknown) { return typeof v === "string" && /^([01]\d|2[0-3]):[0-5]\d$/.test(v); }
function okDate(v: unknown) { return typeof v === "string" && /^\d{4}-\d{2}-\d{2}$/.test(v) && !Number.isNaN(Date.parse(`${v}T00:00:00Z`)); }
function valid(body: Record<string, unknown> | null) { return Boolean(body && typeof body.personId === "string" && body.personId && typeof body.subject === "string" && body.subject.trim() && typeof body.professor === "string" && body.professor.trim() && typeof body.auditorium === "string" && okDate(body.date) && okTime(body.timeStart) && okTime(body.timeEnd) && body.timeStart < body.timeEnd && typeof body.note === "string"); }

export async function GET(request: NextRequest) { if (!auth(request)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); return NextResponse.json({ lessons: await getIndividualLessons() }, { headers: { "Cache-Control": "no-store" } }); }
export async function POST(request: NextRequest) { if (!auth(request)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!valid(body)) return NextResponse.json({ error: "Проверьте дату, время и поля занятия" }, { status: 400 }); const lesson = await saveIndividualLesson({ personId: body.personId as string, subject: (body.subject as string).trim(), professor: (body.professor as string).trim(), auditorium: (body.auditorium as string).trim(), date: body.date as string, timeStart: body.timeStart as string, timeEnd: body.timeEnd as string, note: (body.note as string).trim() }); return NextResponse.json({ lesson }, { status: 201 }); }
export async function PUT(request: NextRequest) { if (!auth(request)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!valid(body) || typeof body.id !== "string") return NextResponse.json({ error: "Проверьте данные занятия" }, { status: 400 }); const lesson = await saveIndividualLesson({ personId: body.personId as string, subject: (body.subject as string).trim(), professor: (body.professor as string).trim(), auditorium: (body.auditorium as string).trim(), date: body.date as string, timeStart: body.timeStart as string, timeEnd: body.timeEnd as string, note: (body.note as string).trim() }, body.id); return NextResponse.json({ lesson }); }
export async function DELETE(request: NextRequest) { if (!auth(request)) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const id = new URL(request.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "Не указано занятие" }, { status: 400 }); await deleteIndividualLesson(id); return NextResponse.json({ ok: true }); }
