"use client";

import { useEffect, useState } from "react";
import type { IndividualLesson, Person } from "@/lib/people";

const blankLesson = (personId=""): IndividualLesson => ({ id:"", personId, subject:"", professor:"", auditorium:"", date:new Date().toISOString().slice(0,10), timeStart:"09:00", timeEnd:"10:30", note:"", createdAt:"", updatedAt:"" });

export default function AdminIndividualsPage(){
 const [people,setPeople]=useState<Person[]>([]); const [lessons,setLessons]=useState<IndividualLesson[]>([]); const [person,setPerson]=useState<Person|null>(null); const [form,setForm]=useState<IndividualLesson|null>(null); const [tab,setTab]=useState<"lessons"|"people">("lessons"); const [message,setMessage]=useState("");
 const load=async()=>{ const [p,l]=await Promise.all([fetch("/api/admin/people",{cache:"no-store"}),fetch("/api/admin/individuals",{cache:"no-store"})]); if(p.status===401){window.location.href="/admin";return;} const pd=await p.json(),ld=await l.json(); setPeople(pd.people??[]);setLessons(ld.lessons??[]); };
 useEffect(()=>{void load()},[]);
 const savePerson=async()=>{if(!person)return;const method=person.id?"PUT":"POST";const r=await fetch("/api/admin/people",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(person)});const d=await r.json();if(!r.ok){setMessage(d.error??"Ошибка");return;}setMessage("Человек сохранён");await load();setPerson(null)};
 const saveLesson=async()=>{if(!form)return;const method=form.id?"PUT":"POST";const r=await fetch("/api/admin/individuals",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setMessage(d.error??"Ошибка");return;}setMessage("Индивидуальное занятие сохранено");await load();setForm(null)};
 const removeLesson=async(id:string)=>{if(!confirm("Удалить занятие?"))return;await fetch(`/api/admin/individuals?id=${encodeURIComponent(id)}`,{method:"DELETE"});await load()};
 const removePerson=async(id:string)=>{if(!confirm("Удалить человека из общего списка?"))return;await fetch(`/api/admin/people?id=${encodeURIComponent(id)}`,{method:"DELETE"});await load()};
 return <main className="admin-shell"><header className="admin-header"><div><p className="admin-eyebrow">Schedule Admin · Люди</p><h1>Индивидуальные</h1><p className="admin-muted">Общий список группы используется для входа, индивидуальных занятий и участников репетиций.</p></div><div className="admin-actions"><a className="admin-secondary admin-link" href="/admin">← Расписание</a><button className="admin-primary" onClick={()=>tab==="people"?setPerson({id:"",name:"",group:1,active:true,createdAt:""}):setForm(blankLesson(people[0]?.id))}>{tab==="people"?"＋ Добавить человека":"＋ Добавить занятие"}</button></div></header>
 <div className="admin-modebar"><button className={tab==="lessons"?"is-active":""} onClick={()=>{setTab("lessons");setPerson(null)}}>Индивидуальные</button><button className={tab==="people"?"is-active":""} onClick={()=>{setTab("people");setForm(null)}}>Люди группы</button></div>
 {message&&<p className="admin-success">{message}</p>}
 {tab==="people"?<section className="admin-card admin-people-list">{people.map(p=><article className="admin-person-row" key={p.id}><div><strong>{p.name}</strong><small>Группа {p.group} · {p.active?"активен":"скрыт"}</small></div><div className="admin-actions"><button className="admin-secondary" onClick={()=>setPerson(p)}>Изменить</button><button className="admin-danger" onClick={()=>removePerson(p.id)}>Удалить</button></div></article>)}{!people.length&&<div className="admin-empty">Добавь людей группы — после этого они появятся на экране входа.</div>}</section>:<section className="admin-card admin-individual-list">{form&&<div className="admin-individual-form"><h2>{form.id?"Редактирование":"Новое индивидуальное занятие"}</h2><div className="admin-form-grid admin-form-grid-main"><label>Студент<select className="admin-input" value={form.personId} onChange={e=>setForm({...form,personId:e.target.value})}>{people.map(p=><option key={p.id} value={p.id}>{p.name} · гр. {p.group}</option>)}</select></label><label>Предмет<input className="admin-input" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Например, вокал"/></label><label>Преподаватель<input className="admin-input" value={form.professor} onChange={e=>setForm({...form,professor:e.target.value})}/></label><label>Аудитория<input className="admin-input" value={form.auditorium} onChange={e=>setForm({...form,auditorium:e.target.value})}/></label><label>Дата<input className="admin-input" type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Начало<input className="admin-input" type="time" value={form.timeStart} onChange={e=>setForm({...form,timeStart:e.target.value})}/></label><label>Конец<input className="admin-input" type="time" value={form.timeEnd} onChange={e=>setForm({...form,timeEnd:e.target.value})}/></label><label>Заметка<input className="admin-input" value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Необязательно"/></label></div><div className="admin-actions"><button className="admin-secondary" onClick={()=>setForm(null)}>Отмена</button><button className="admin-primary" onClick={()=>void saveLesson()}>Сохранить</button></div></div>}{lessons.map(l=><article className="admin-person-row" key={l.id}><div><strong>{people.find(p=>p.id===l.personId)?.name??"Неизвестный студент"} · {l.subject}</strong><small>{l.date} · {l.timeStart}–{l.timeEnd} · {l.professor}{l.auditorium?` · ${l.auditorium}`:""}</small></div><div className="admin-actions"><button className="admin-secondary" onClick={()=>setForm(l)}>Изменить</button><button className="admin-danger" onClick={()=>removeLesson(l.id)}>Удалить</button></div></article>)}{!lessons.length&&!form&&<div className="admin-empty">Индивидуальных занятий пока нет.</div>}</section>}
 {person&&<div className="admin-modal-backdrop"><div className="admin-modal admin-card"><h2>{person.id?"Изменить человека":"Новый человек"}</h2><label>Имя<input className="admin-input" autoFocus value={person.name} onChange={e=>setPerson({...person,name:e.target.value})} placeholder="Имя и фамилия"/></label><label>Группа<select className="admin-input" value={person.group} onChange={e=>setPerson({...person,group:Number(e.target.value) as 1|2})}><option value="1">1</option><option value="2">2</option></select></label><label className="admin-checkbox"><input type="checkbox" checked={person.active} onChange={e=>setPerson({...person,active:e.target.checked})}/> Показывать при входе</label><div className="admin-actions"><button className="admin-secondary" onClick={()=>setPerson(null)}>Отмена</button><button className="admin-primary" onClick={()=>void savePerson()}>Сохранить</button></div></div></div>}
 </main>
}
