"use client";
import { useEffect, useMemo, useState } from "react";
import type { IndividualSlot } from "@/lib/individual-slots";

type SlotForm={subject:string;professor:string;auditorium:string;date:string;timeStart:string;durationMinutes:number;note:string;capacity:number;count:number;intervalMinutes:number};
const blank=():SlotForm=>({subject:"",professor:"",auditorium:"",date:new Date().toISOString().slice(0,10),timeStart:"09:00",durationMinutes:90,note:"",capacity:1,count:1,intervalMinutes:90});
const toMinutes=(v:string)=>{const [h,m]=v.split(":").map(Number);return h*60+m};
const fromMinutes=(v:number)=>`${String(Math.floor(v/60)%24).padStart(2,"0")}:${String(v%60).padStart(2,"0")}`;
const toForm=(s:IndividualSlot):SlotForm=>({...s,count:1,intervalMinutes:Math.max(1,toMinutes(s.timeEnd)-toMinutes(s.timeStart)),durationMinutes:Math.max(1,toMinutes(s.timeEnd)-toMinutes(s.timeStart))});
const usedSeats=(s:IndividualSlot)=>s.studentIds?.length??0;
export default function IndividualSlotsAdmin(){
 const [slots,setSlots]=useState<IndividualSlot[]>([]),[subjects,setSubjects]=useState<string[]>([]),[form,setForm]=useState<SlotForm|null>(null),[editId,setEditId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[filter,setFilter]=useState("all");
 const load=async()=>{setLoading(true);const r=await fetch("/api/admin/individual-slots",{cache:"no-store"});if(r.status===401){window.location.href="/admin";return}const d=await r.json();setSlots(d.slots??[]);setSubjects(d.subjects??[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const save=async()=>{if(!form||!form.subject||!form.professor||!form.date||form.durationMinutes<1||form.capacity<1||form.count<1||form.intervalMinutes<1){setMessage("Проверь поля, длительность, вместимость и интервал");return}const end=toMinutes(form.timeStart)+form.durationMinutes;if(end>1440){setMessage("Занятие выходит за пределы суток");return}setSaving(true);const timeEnd=fromMinutes(end);const url=editId?"/api/admin/individual-slots":"/api/admin/individual-slots/batch";const body=editId?{...form,timeEnd,id:editId}:{...form,timeEnd};const r=await fetch(url,{method:editId?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setSaving(false);if(!r.ok){setMessage(d.error??"Ошибка сохранения");return}setForm(null);setEditId("");setMessage(editId?"Слот обновлён":`Создано слотов: ${d.slots?.length??1}`);await load()};
 const remove=async(id:string)=>{if(!confirm("Удалить слот?"))return;await fetch(`/api/admin/individual-slots?id=${encodeURIComponent(id)}`,{method:"DELETE"});await load()};
 const visible=useMemo(()=>slots.filter(s=>filter==="all"||(filter==="free"?usedSeats(s)<(s.capacity??1):usedSeats(s)>0)),[slots,filter]);
 if(loading)return <main className="slots-admin"><div className="slots-spinner"/><p>Загрузка слотов…</p></main>;
 return <main className="slots-admin"><header className="slots-head"><div><a href="/admin">← Админка</a><p>ИНДИВИДУАЛЬНЫЕ</p><h1>Слоты</h1><span>Создавай одиночные занятия или сразу серию.</span></div><button onClick={()=>{setEditId("");setForm(blank())}}>＋ Добавить занятия</button></header>
 <section className="slots-toolbar"><div><strong>{slots.length}</strong><span>слотов</span></div><div><strong>{slots.filter(s=>usedSeats(s)<(s.capacity??1)).length}</strong><span>свободно</span></div><div><strong>{slots.reduce((n,s)=>n+usedSeats(s),0)}</strong><span>записей</span></div><nav>{[["all","Все"],["free","Свободные"],["taken","Занятые"]].map(([x,l])=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{l}</button>)}</nav></section>
 {message&&<p className="slots-message">{message}</p>}<section className="slots-list">{visible.length?visible.map(s=>{const used=usedSeats(s),cap=s.capacity??1;return <article className="slot-card" key={s.id}><div className="slot-date"><strong>{new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short"}).format(new Date(`${s.date}T12:00:00`))}</strong><span>{s.timeStart}–{s.timeEnd}</span></div><div className="slot-info"><strong>{s.subject}</strong><span>{s.professor}{s.auditorium?` · ${s.auditorium}`:""}</span>{s.note&&<small>{s.note}</small>}</div><div className={`slot-status ${used>=cap?"taken":"free"}`}>{used}/{cap}</div><div className="slot-actions"><button onClick={()=>{setEditId(s.id);setForm(toForm(s))}}>Изменить</button><button onClick={()=>void remove(s.id)}>Удалить</button></div></article>}) : <div className="slots-empty">Слотов пока нет.</div>}</section>
 {form&&<div className="slots-overlay" onMouseDown={()=>setForm(null)}><section className="slots-modal" onMouseDown={e=>e.stopPropagation()}><header><div><p>{editId?"СЛОТ":"СЕРИЯ СЛОТОВ"}</p><h2>{editId?"Изменить слот":"Добавить занятия"}</h2></div><button onClick={()=>setForm(null)}>×</button></header><div className="slots-form"><label>Предмет<select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}><option value="">Выбери предмет</option>{subjects.map(s=><option key={s} value={s}>{s}</option>)}</select></label><label>Преподаватель<input value={form.professor} onChange={e=>setForm({...form,professor:e.target.value})}/></label><label>Аудитория<input value={form.auditorium} onChange={e=>setForm({...form,auditorium:e.target.value})}/></label><label>Дата<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><div className="slot-times"><label>Начало<input type="time" value={form.timeStart} onChange={e=>setForm({...form,timeStart:e.target.value})}/></label><label>Длительность (мин)<input type="number" min="1" max="1440" value={form.durationMinutes} onChange={e=>setForm({...form,durationMinutes:Number(e.target.value)})}/></label></div><div className="slot-times"><label>Количество мест<input type="number" min="1" max="100" value={form.capacity} onChange={e=>setForm({...form,capacity:Number(e.target.value)})}/></label>{!editId&&<label>Количество занятий<input type="number" min="1" max="100" value={form.count} onChange={e=>setForm({...form,count:Number(e.target.value)})}/></label>}</div>{!editId&&<label>Интервал между началами (мин)<input type="number" min="1" max="1440" value={form.intervalMinutes} onChange={e=>setForm({...form,intervalMinutes:Number(e.target.value)})}/></label>}<label>Комментарий<textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><footer><button onClick={()=>setForm(null)}>Отмена</button><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?"Сохраняю…":"Сохранить"}</button></footer></section></div>}</main>;
}
